CREATE TABLE PLAYER (
    ID INT NOT NULL GENERATED ALWAYS AS IDENTITY,
    Name VARCHAR(100),
    Email VARCHAR(100),
    Password VARCHAR(100),
    Gender VARCHAR(10),
    Score INT,
    PRIMARY KEY (ID)
);

-- Recreate the SESSION table with correct uppercase column names
CREATE TABLE SESSION (
    ID INT NOT NULL GENERATED ALWAYS AS IDENTITY,
    PLAYER1ID INT NOT NULL,
    PLAYER2ID INT NOT NULL,
    PLAYER1NAME VARCHAR(100),
    PLAYER2NAME VARCHAR(100),
    PLAYER1SCORE INT,
    PLAYER2SCORE INT,
    PRIMARY KEY (ID),
    CONSTRAINT fk_player1
        FOREIGN KEY (PLAYER1ID)
        REFERENCES PLAYER(ID),
    CONSTRAINT fk_player2
        FOREIGN KEY (PLAYER2ID)
        REFERENCES PLAYER(ID)
);